use_frameworks!

platform :ios, '8.0'

target 'HGImageBrowser_Example' do
  pod 'HGImageBrowser', :path => '../'
  pod 'TZImagePickerController'
  
  target 'HGImageBrowser_Tests' do
    inherit! :search_paths

    
  end
end
